### ISSUE TITLE
Sound Editing

### ISSUE THREAD

**Issue by tevko** [charlespeters/viewsource#8]
Here are a few sound editing resources I found

* [online sound editor, works with soundcloud, currently free in beta](https://twistedwave.com/online/)
* [online music studio with recording, effects, virtual instruments and over 700 free loops and sounds](http://soundation.com/)
* [free, easy-to-use, multi-track audio editor and recorder for Windows, Mac OS X, GNU/Linux and other operating systems](http://audacity.sourceforge.net/download/)

**Comment by charlespeters** [comment]
This issue was moved to charlespeters/viewsourc.es#3
